Update: dart affix search condition generator and other minor fixes
hpc-io/pdc pull request #138
Opened 2023-09-07 18:32 UTC by zhangwei217245

1. dart affix search condition generator 
2. CMake server cache size setting, 
3. some compiler warnings in pdc_tools.

2023-09-07 21:23 UTC, houjun approved these changes

2023-09-07 21:28 UTC, jeanbez commented
@zhangwei217245 can you make sure your branch is updated with the latest .yml files from develop and stable? That way the CI in NERSC will be able to start.

2023-09-07 21:29 UTC, houjun requested changes
see Jean Luca's comment

2023-09-08 00:29 UTC, zhangwei217245 commented
> 



> @zhangwei217245 can you make sure your branch is updated with the latest .yml files from develop and stable? That way the CI in NERSC will be able to start.

Hi, @jeanbez , this branch is in sync with the develop branch of the GitHub upstream repo. Do I need to perform anything particular to sync the .yml files? If there is no diff on .yml files, I guess mostly those files are already in sync. 
Is the automatic NERSC CI triggering supported now? If not, I can push this branch to the NERSC CI repo to trigger a run.

2023-09-14 19:05 UTC, closed without merging