Complete support for Docker and Github Codespace (#9)
hpc-io/pdc pull request #157
Opened 2023-10-13 19:42 UTC by zhangwei217245

Now we can run our dev environment with the support of Docker and we can save some node hours for NERSC.

2023-10-20 16:21 UTC, zhangwei217245 commented
Tested for NERSC-ci: 

![image](https://github.com/hpc-io/pdc/assets/346451/fc87c051-6124-4fe0-9f82-743a0dccca0c)
![image](https://github.com/hpc-io/pdc/assets/346451/d5b08c80-c151-4476-be04-43d27e658723)
![image](https://github.com/hpc-io/pdc/assets/346451/995e3ff1-cb6e-4595-bce8-805701c4d232)

2023-10-26 18:32 UTC, houjun approved these changes

2023-10-31 19:45 UTC, jeanbez requested changes

2023-10-31 19:45 UTC, jeanbez commented on .devcontainer/devcontainer.Dockerfile
> +FROM zhangwei217245/pdc_dev_base:latest
Let's move this to our own registry

2023-10-31 19:45 UTC, jeanbez commented on .docker/run_dev_base.sh
> +    docker image rm -f zhangwei217245/pdc_dev_base:latest
Move to new URL

2023-10-31 19:45 UTC, jeanbez commented on .docker/run_dev_base.sh
> +    docker create -it -v $(pwd):${DEFAULT_WORKSPACE} -w ${DEFAULT_WORKSPACE} --entrypoint /bin/bash zhangwei217245/pdc_dev_base:latest
Here are well

2023-10-31 19:49 UTC, zhangwei217245 commented on .docker/run_dev_base.sh
> +    docker create -it -v $(pwd):${DEFAULT_WORKSPACE} -w ${DEFAULT_WORKSPACE} --entrypoint /bin/bash zhangwei217245/pdc_dev_base:latest
will make changes!

2023-10-31 20:17 UTC, zhangwei217245 commented on .docker/run_dev_base.sh
> +    docker image rm -f zhangwei217245/pdc_dev_base:latest
addressed

2023-10-31 20:17 UTC, zhangwei217245 commented on .docker/run_dev_base.sh
> +    docker image rm -f zhangwei217245/pdc_dev_base:latest
addressed

2023-10-31 20:17 UTC, zhangwei217245 commented on .docker/run_dev_base.sh
> +    docker create -it -v $(pwd):${DEFAULT_WORKSPACE} -w ${DEFAULT_WORKSPACE} --entrypoint /bin/bash zhangwei217245/pdc_dev_base:latest
addressed

2023-10-31 20:19 UTC, jeanbez approved these changes

2023-10-31 22:04 UTC, merged