Update CMakeLists.txt to bump version number
hpc-io/pdc pull request #202
Opened 2024-06-12 17:15 UTC by jeanbez

# Related Issues / Pull Requests

None

# Description

Bump hardcoded version number in CMakeLists.txt

# What changes are proposed in this pull request?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected; for instance, examples in this repository must be updated too)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code modifies existing public API, or introduces new public API, and I updated or wrote docstrings
- [ ] I have commented my code
- [ ] My code requires documentation updates, and I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2024-07-03 17:37 UTC, houjun approved these changes

2024-09-05 18:10 UTC, zhangwei217245 approved these changes

2024-09-05 18:11 UTC, zhangwei217245 requested changes
do we need to perform this formatter change?

2024-09-05 18:12 UTC, jeanbez commented
> do we need to perform this formatter change?

yes, the CI was broken for a python import since we used a very old version

2024-09-05 20:59 UTC, zhangwei217245 approved these changes

2024-09-05 20:59 UTC, zhangwei217245 commented on .github/workflows/clang-format-check.yml
> +      uses: DoozyX/clang-format-lint-action@v0.18.1
AFAIK, there seem to be some incompatibility for the clang-format tool for different versions. If we change the version here, it would possibly cause a total reformatting of the source code everywhere... 

Are we ready for this ?

2024-09-05 20:59 UTC, zhangwei217245 commented on .github/workflows/clang-format-check.yml
> +      uses: DoozyX/clang-format-lint-action@v0.18.1
checked that plugin, v0.18.1 is the version of that plugin, but not the formatter itself. Should be okay to proceed.

2024-09-05 21:00 UTC, merged