IDIOMS Update & BULKI v0.1
hpc-io/pdc pull request #203
Opened 2024-06-24 03:40 UTC by zhangwei217245

# Related Issues / Pull Requests

Will update later. 

# Description

Major changes: 

* IDIOMS -> affix-based query benchmark
* IDIOMS -> index persistence mechanism
* IDIOMS -> numeric value query support (exact query and range query)
* IDIOMS -> numeric value query benchmark
* IDIOMS -> simulation test
* BULKI V0.1 -> a data serialization and deserialization mechanism
* Metadata JSON validator
* Metadata JSON Loader for PDC

Minor changes
* Updated Dockerfile for faster docker image build
* Updated pdc_generic.h for full data type support capability and better ordering of PDC data type enums

In-progress changes
* Some code for multi-condition query.

# What changes are proposed in this pull request?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected; for instance, examples in this repository must be updated too)
- [ x ] This change requires a documentation update

# Checklist:

- [ ] My code modifies existing public API, or introduces new public API, and I updated or wrote docstrings
- [ x ] I have commented my code
- [ ] My code requires documentation updates, and I have made corresponding changes to the documentation
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes

2024-07-01 17:16 UTC, jeanbez requested changes

2024-07-01 17:16 UTC, jeanbez commented on src/api/pdc_client_connect.c
> -    return ret;
Just confirming: why we do not need a return code anymore?

2024-07-01 17:16 UTC, jeanbez commented on src/api/pdc_client_connect.c
> +        return;
Just confirming: why do we not need a return code anymore?

2024-07-01 17:16 UTC, jeanbez commented on src/commons/generic/include/pdc_generic_old.h
> +#ifndef PDC_GENERIC_H
Do we need this _old.h file?

2024-07-01 17:16 UTC, jeanbez commented on src/commons/index/dart/index/hashtable/hashtable_impl.c
> +
This entire file commented out, do we still need it or can we remove it?

2024-07-01 17:16 UTC, jeanbez commented on src/commons/index/dart/index/hashtable/include/hashtable_impl.h
> +
Same for this file, is it still needed?

2024-07-01 17:16 UTC, jeanbez commented on src/server/include/pdc_server.h
> -#include "pdc_hash-table.h"
The header file seems to be removed in the PR, but it is still included. Is this correct?

2024-07-01 17:16 UTC, jeanbez commented on src/server/include/pdc_server_metadata.h
> -#include "pdc_hash-table.h"
The header file seems to be removed in the PR, but it is still included. Is this correct?

2024-07-01 17:16 UTC, jeanbez commented on CMakeLists.txt
> +  set(SUPPRESSED_LIST "-Wno-use-after-free" ${SUPPRESSED_LIST})
Why are we suppressing those?

2024-07-01 17:16 UTC, jeanbez commented on src/commons/index/dart/index/idioms/idioms_local_index_test.c
Can we have all the tests in the default pdc test directory instead of mixed in with the rest of the code?

2024-07-01 17:16 UTC, jeanbez commented on src/commons/logging/pdc_logger.c
DIdn't we have a logger in PDC already? Is this used only for IDIOMS?

2024-07-02 00:27 UTC, zhangwei217245 commented on src/commons/logging/pdc_logger.c
AFAIK, there is no logger that controls different level of logging.

2024-07-02 00:30 UTC, zhangwei217245 commented on src/commons/index/dart/index/idioms/idioms_local_index_test.c
This is a unit test to test the idioms_local_index rather than an end-to-end test. After discussing with Dr. Tang, we decided to add such unit test in the src directory, close to the module/function it is testing.

2024-07-02 00:38 UTC, zhangwei217245 commented on src/server/include/pdc_server_metadata.h
> -#include "pdc_hash-table.h"
the "pdc_hash-table.h" is different than "pdc_hash_table.h" in terms of the file name and location. But both files contain the same implementation. After this change, we only have one location for the pdc_hash_table which is located in pdc_commons. This helps with avoid redundant code as well as inconsistency between two copies of the exact same code.

2024-07-02 00:39 UTC, zhangwei217245 commented on src/server/include/pdc_server.h
> -#include "pdc_hash-table.h"
the "pdc_hash-table.h" is different than "pdc_hash_table.h" in terms of the file name and location. But both files contain the same implementation. After this change, we only have one location for the pdc_hash_table which is located in pdc_commons. This helps with avoid redundant code as well as inconsistency between two copies of the exact same code.

2024-07-02 00:45 UTC, zhangwei217245 commented on src/api/pdc_client_connect.c
> +        return;
The previous implementation was taking serverID and returning a dart_server struct instance that contains the indexed_word_count as well as request_count fields. However, when writing the simulator test of IDIOMS, I realize that we can send a dart_server pointer as an input, which can pass in the server ID, while still be able to take the result information of the function. This simplifies the implementation of , not only the simulator test, but also everywhere else in IDIOMS.

2024-07-02 00:46 UTC, zhangwei217245 commented on src/api/pdc_client_connect.c
> -    return ret;
The previous implementation was taking serverID and returning a dart_server struct instance that contains the indexed_word_count as well as request_count fields. However, when writing the simulator test of IDIOMS, I realize that we can send a dart_server pointer as an input, which can pass in the server ID, while still be able to take the result information of the function. This simplifies the implementation of , not only the simulator test, but also everywhere else in IDIOMS.

2024-07-02 00:48 UTC, zhangwei217245 commented on src/commons/generic/include/pdc_generic_old.h
> +#ifndef PDC_GENERIC_H
since all the existing test passed, I don't think we need this anymore.

2024-07-02 00:53 UTC, zhangwei217245 commented on CMakeLists.txt
> +  set(SUPPRESSED_LIST "-Wno-use-after-free" ${SUPPRESSED_LIST})
these are some warnings that can be ignored. Given the complexity of our PDC implementation, these warnings are not very sense-making in our project and there is marginal  value for fixing these warnings in the code.

We need a cleaner compilation log to highlight the compilation errors that really matters.

2024-07-02 00:55 UTC, zhangwei217245 commented on src/commons/index/dart/index/hashtable/hashtable_impl.c
> +
This is for the controlled experiment in the DART paper (for full-string hash and prefix hashing). But now, this is not used.
Let's leave this here for this version. Will possibly need it somewhere in the future.

2024-07-02 00:55 UTC, zhangwei217245 commented on src/commons/index/dart/index/hashtable/include/hashtable_impl.h
> +
This is for the controlled experiment in the DART paper (for full-string hash and prefix hashing). But now, this is not used.
Let's leave this here for this version. Will possibly need it somewhere in the future.

2024-07-02 04:39 UTC, jeanbez commented on src/commons/generic/include/pdc_generic_old.h
> +#ifndef PDC_GENERIC_H
Got it! Could you remove this file, then? If needed we can get it back for git

2024-07-02 04:40 UTC, jeanbez commented on src/server/include/pdc_server.h
> -#include "pdc_hash-table.h"
Oh, I see; I missed the slight difference in the filename.

2024-07-02 16:36 UTC, zhangwei217245 commented on src/commons/generic/include/pdc_generic_old.h
> +#ifndef PDC_GENERIC_H
Sure, let's remove it.

2024-07-02 17:40 UTC, houjun commented on CMakeLists.txt
> +  set(SUPPRESSED_LIST "-Wno-use-after-free" ${SUPPRESSED_LIST})
-Wno-use-after-free should probably be removed from here, is there an example code segment and compiler warning message that shows it is not helping?

2024-07-05 00:54 UTC, zhangwei217245 commented
After first round of PR review, the following are needed:

1. an End-to-end CI test of IDIOMS APIs
2. developer notes documentation about IDIOMS APIs, regarding the parameters and different query expressions
3. developer notes documentation about BULKI, regarding the demo showcasing its usage.

2024-07-05 01:48 UTC, zhangwei217245 commented on CMakeLists.txt
> +  set(SUPPRESSED_LIST "-Wno-use-after-free" ${SUPPRESSED_LIST})
![image](https://github.com/hpc-io/pdc/assets/346451/d25b996c-81d3-47da-b22f-815def85030a)
![image](https://github.com/hpc-io/pdc/assets/346451/fcdb6a39-f972-4737-b0f7-ffa2ea226317)

2024-09-05 18:06 UTC, zhangwei217245 commented on src/commons/generic/include/pdc_generic_old.h
> +#ifndef PDC_GENERIC_H
addressed.

2024-09-05 18:07 UTC, zhangwei217245 commented on src/commons/index/dart/index/hashtable/include/hashtable_impl.h
> +
Leave it as is.

2024-09-05 18:08 UTC, jeanbez commented on src/commons/logging/pdc_logger.c
could we use the PDC_DEBUG to set this?

2024-09-05 20:29 UTC, houjun requested changes

2024-09-05 20:29 UTC, houjun commented on src/tests/CMakeLists.txt
> +else()
The CI tests seem to fail around here

2024-09-05 20:37 UTC, zhangwei217245 commented on src/tests/CMakeLists.txt
> +else()
noticed. now fixed.

2024-09-05 20:48 UTC, houjun commented
@jeanbez @zhangwei217245, any idea why the clang-format fix is not triggered and the clang-format check keeps failing?

2024-09-05 21:36 UTC, houjun commented
@zhangwei217245, some parallel tests on Permlutter tests are failing, see [the logs](https://software.nersc.gov/hpc-io/pdc-nersc/-/pipelines/98113)

2024-09-05 21:40 UTC, jeanbez requested changes
Please remove the `src/api/test_bulki.bin` file unless there is a need for it to be there.

2024-09-05 21:57 UTC, zhangwei217245 commented
> @zhangwei217245, some parallel tests on Permlutter CI are failing, see [the logs](https://software.nersc.gov/hpc-io/pdc-nersc/-/pipelines/98113)
> 
> > ```
> >   Start 139: idioms_ci_mpi
> >      24/24 Test #139: idioms_ci_mpi ....................***Failed    7.79 sec
> >      96% tests passed, 1 tests failed out of 24
> > ```
There should not be parallel test case for now. I just removed it from CMake.

2024-09-05 21:58 UTC, zhangwei217245 commented
> Please remove the `src/api/test_bulki.bin` file unless there is a need for it to be there.

Removed. Thank you for reminding.

2024-09-05 22:14 UTC, zhangwei217245 commented
Plus: I don't have access to software.nersc.gov


![image](https://github.com/user-attachments/assets/b2d28d55-b54f-40b4-8512-3e2421d268e6)

2024-09-06 01:20 UTC, houjun approved these changes

2024-09-06 21:31 UTC, jeanbez approved these changes

2024-09-10 12:03 UTC, sbyna approved these changes

2024-09-10 13:10 UTC, merged