Eqsim
hpc-io/pdc pull request #213
Opened 2024-10-23 20:20 UTC by houjun

# Related Issues / Pull Requests

List all related issues and/or pull requests if there are any.

# Description
- Add EQSIM-related benchmark code
- Add (partial) support for ZFP compression
- Fix an issue with data querying

# What changes are proposed in this pull request?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected; for instance, examples in this repository must be updated too)
- [x] This change requires a documentation update

# Checklist:

- [ ] My code modifies existing public API, or introduces new public API, and I updated or wrote docstrings
- [x] I have commented my code
- [x] My code requires documentation updates, and I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-11-04 19:12 UTC, houjun commented
@jeanbez @zhangwei217245

2024-11-04 19:37 UTC, jeanbez requested changes

2024-11-04 19:37 UTC, jeanbez commented on src/api/pdc_region/pdc_region_transfer.c
> +            // Tang
Can we drop this line and possibly the commented-out lines?

2024-11-04 19:37 UTC, jeanbez commented on src/api/pdc_region/pdc_region_transfer.c
> +            // Tang
Can we drop this line and possibly the commented-out lines?

2024-11-04 19:37 UTC, jeanbez commented on src/server/pdc_server_region/pdc_server_data.c
> +                // data_sieving_g = 1 by default, export PDC_DATA_SIEVING=0 to change
We need to also change the documentation if this is the default now.

2024-11-04 19:37 UTC, jeanbez commented on src/server/pdc_server_region/pdc_server_data.c
> +#ifdef ENABLE_ZFP
This compression part is only relevant to the EQSIM code, or can it be used by any other test/code? Can we add something in the documentation for either case, including the option we need to enable/disable this?

2024-11-04 19:37 UTC, jeanbez commented on src/server/pdc_server_region/pdc_server_region_cache.c
> +#define MAX_CACHE_SIZE_GB PDC_SERVER_CACHE_MAX_GB
We need to make sure the docs are updated correctly with the env name and unit people should use.

2024-11-04 19:37 UTC, jeanbez commented on src/server/pdc_server_region/pdc_server_region_cache.c
> +    env_char = getenv("PDC_SERVER_CACHE_NO_FLUSH");
Was the doc updated for this env?

2024-11-26 18:35 UTC, jeanbez approved these changes

2024-11-26 19:45 UTC, zhangwei217245 approved these changes

2024-12-02 20:39 UTC, merged